version: '2.0'
services:
  web:
    privileged: true
    build: web/docker
    depends_on:
      - db
      - ds1
      - ds2
      - ds3
    volumes:
      - ./moodle:/mnt/moodle
      - ./initialdata:/var/www/initialdata
      - moodledata:/var/www/moodledata
    tmpfs:
      - /var/www/local/cachedir
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_WEB_HOST: web
    ports:
      - 8980:80
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "m@0dl3ing"
      POSTGRES_DB: moodle
    volumes:
      - ./db/docker-entrypoint-initdb.d:/db/docker-entrypoint-initdb.d
      - "dbdata:/var/lib/postgresql/data"
  ds1:
    image: gluster/gluster-centos
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  ds2:
    image: gluster/gluster-centos
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    expose:
      - 111
      - 245
      - 443
      - 2049
      - 2222
      - 6010-6012
      - 8080
      - 24000-25000
      - 38465-38466
      - 38468-38469
      - 49152-49154
      - 49156-49162
  ds3:
    image: gluster/gluster-centos
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
volumes:
  dbdata:
  moodledata:
